export enum MotivoReportePregunta {
    RESPUESTA_INCORRECTA = 'RESPUESTA INCORRECTA',
    PREGUNTA_MAL_FORMULADA = 'PREGUNTA MAL FORMULADA',
    PREGUNTA_DIFICIL = 'PREGUNTA DIFICIL',
    PREGUNTA_IRRELEVANTE = 'PREGUNTA IRRELEVANTE',
    PREGUNTA_DUPLICADA= 'PREGUNTA DUPLICADA',
    OTROS= 'OTROS'
    }
  